### ISSUE TITLE
Pass along parameters

### ISSUE THREAD

**Issue by robiningelbrecht** [hussainweb/drupal-api-client#1]
I would like to get the releases of a certain project, this can be done by requesting something like this:
https://www.drupal.org/api-d7/node.json?type=project_release&field_release_project=my_project_id

How would I do this with your API? Or is this not possible?

**Comment by robiningelbrecht** [comment]
Well I thik I found the solution myself. I should use "NodeCollectionRequest.php" shouldn't I? Wehere I can pass along params

**Comment by hussainweb** [comment]
You're right. All request classes contain a mechanism to specify query parameters. See this for your example:

```
$client = new Client();
$request = new NodeCollectionRequest([
    'type' => 'project_release',
    'field_release_project' => $my_project_id,
]);
$nodes = $client->getEntity($request);
```

In the above, `$nodes` will be of type `\Hussainweb\DrupalApi\Entity\Collection\NodeCollection`.

If you want a more elaborate/complicated example, see https://github.com/hussainweb/drupal-stats/blob/master/app/DrupalStats/Jobs/RetrieveNodeCollectionJob.php.

**Comment by hussainweb** [comment]
Closing issue now, please reopen if you need more help on this.

**Comment by robiningelbrecht** [comment]
Works like a charm, thanks for this awesome library!!!
